[package]
name = "memx"
version = "0.1.11"
authors = ["aki <aki.akaguma@hotmail.com>"]
edition = "2018"
description = "memory functions like a libc memcmp(), memchr(), memmem(), memcpy(), memset()"
keywords = ["memcmp", "memchr", "memmem"]
categories = ["algorithms"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/aki-akaguma/memx"

[features]
default = ["std"]
std = []
cmp_bytes = []

[dependencies]

[dev-dependencies]

[workspace]
members = [
    "xtask",
    "xbench",
]
