[package]
name = "memx"
version = "0.1.2"
authors = ["aki <aki.akaguma@hotmail.com>"]
edition = "2018"
description = "memory functions like a libc memcmp(), memchr(), memmem(), memcpy(), memset()"
keywords = ["memcmp", "memchr", "memmem"]
categories = ["algorithms"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/aki-akaguma/memx"

[features]
default = []
cmp_bytes = []

[dependencies]

[dev-dependencies]
criterion = "0.3"
memchr = "2.4"

[workspace]
members = [
    "xtask",
]

[[bench]]
name = "bench-memchr"
path = "benches/bench-memchr.rs"
harness = false

[[bench]]
name = "bench-memcmp"
path = "benches/bench-memcmp.rs"
harness = false

[[bench]]
name = "bench-memcpy"
path = "benches/bench-memcpy.rs"
harness = false

[[bench]]
name = "bench-memeq"
path = "benches/bench-memeq.rs"
harness = false

[[bench]]
name = "bench-memmem"
path = "benches/bench-memmem.rs"
harness = false

[[bench]]
name = "bench-memset"
path = "benches/bench-memset.rs"
harness = false
