name: Test-mac

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test rust ${{matrix.rust}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        rust: [beta, stable, 1.60.0]
        os: [macos-latest]
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{matrix.rust}}
          components: rust-src
      - run: cargo test
